name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd website
          npm install

      - name: Build project
        run: |
          cd website
          npm run build

      - name: Clean git working directory
        run: |
          git clean -fdx
          git reset --hard

      - name: List dist contents
        run: |
          ls -lh website/dist
          du -sh website/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
          force_orphan: true
          allow_empty_commit: true
          debug: true
